version: 2

sources:
  - name: source # schema where source tables are
    database: dbt_dev
    tables:
      - name: dim_customers
      - name: dim_customer_address
      - name: dim_customer_orders
      - name: dim_products